name: com_decom
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _r-mutex=1.0.1
  - amply=0.1.6
  - annotated-types=0.7.0
  - appdirs=1.4.4
  - argparse-dataclass=2.0.0
  - attrs=25.4.0
  - bc=1.07.1
  - bedtools=2.31.1
  - binutils=2.44
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - blas=2.138
  - blas-devel=3.9.0
  - bottleneck=1.6.0
  - brotli-python=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-compiler=1.11.0
  - ca-certificates=2025.11.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.3.0
  - cni=1.0.1
  - cni-plugins=1.3.0
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.6
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - compilers=1.11.0
  - conda-gcc-specs=14.3.0
  - conda-inject=1.3.2
  - configargparse=1.7.1
  - connection_pool=0.0.3
  - curl=8.17.0
  - cxx-compiler=1.11.0
  - cython=3.1.4
  - dfam=3.7
  - docutils=0.22.3
  - dpath=2.2.0
  - eido=0.2.4
  - entrez-direct=22.4
  - exceptiongroup=1.3.0
  - expat=2.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fortran-compiler=1.11.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gfortran=14.3.0
  - gfortran_impl_linux-64=14.3.0
  - gfortran_linux-64=14.3.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h2=4.3.0
  - h5py=3.15.1
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - hmmer=3.4
  - hpack=4.1.0
  - htslib=1.22.1
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - immutables=0.21
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - jq=1.8.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_core=5.9.1
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - less=679
  - libaec=1.1.4
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.1
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsanitizer=14.3.0
  - libseccomp=2.4.4
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - logmuse=0.2.8
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.4.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mpi=1.0
  - nbformat=5.10.4
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy=2.3.4
  - numpy-base=2.3.4
  - oniguruma=6.9.10
  - openblas=0.3.30
  - openmpi=4.1.6
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - parallel=20250822
  - pcre2=10.46
  - pephubclient=0.4.4
  - peppy=0.40.8
  - perl=5.32.1
  - perl-archive-tar=3.04
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.214
  - perl-compress-raw-zlib=2.214
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.213
  - perl-io-zlib=1.15
  - perl-json=4.10
  - perl-json-xs=4.04
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.70
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pip=25.2
  - pixman=0.46.4
  - plac=1.4.5
  - platformdirs=4.5.0
  - pluggy=1.6.0
  - psutil=7.1.3
  - pthread-stubs=0.3
  - pulp=2.8.0
  - pycparser=2.22
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.11.6
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-tzdata=2025.2
  - python-wget=3.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - r-base=4.3.3
  - r-cli=3.6.1
  - r-cpp11=0.5.2
  - r-glue=1.6.2
  - r-igraph=2.1.4
  - r-lattice=0.22_5
  - r-lifecycle=1.0.3
  - r-magrittr=2.0.3
  - r-matrix=1.6_1.1
  - r-pkgconfig=2.0.3
  - r-rlang=1.1.1
  - r-vctrs=0.6.4
  - readline=8.3
  - referencing=0.37.0
  - repeatmasker=4.2.1
  - requests=2.32.5
  - reretry=0.11.8
  - rich=14.2.0
  - rmblast=2.14.1
  - rpds-py=0.28.0
  - samtools=1.22.1
  - sed=4.9
  - setuptools=80.9.0
  - shellingham=1.5.4
  - singularity=3.8.6
  - six=1.17.0
  - slack-sdk=3.37.0
  - slack_sdk=3.37.0
  - smart_open=7.4.4
  - smmap=5.0.2
  - snakemake=9.13.5
  - snakemake-interface-common=1.22.0
  - snakemake-interface-executor-plugins=9.3.9
  - snakemake-interface-logger-plugins=2.0.0
  - snakemake-interface-report-plugins=1.3.0
  - snakemake-interface-scheduler-plugins=2.0.2
  - snakemake-interface-storage-plugins=4.2.3
  - snakemake-minimal=9.13.5
  - sqlite=3.50.2
  - squashfs-tools=4.6.1
  - sysroot_linux-64=2.28
  - tabulate=0.9.0
  - throttler=1.2.2
  - tk=8.6.15
  - tktable=2.10
  - tomli=2.3.0
  - traitlets=5.14.3
  - trf=4.10.0rc2
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ubiquerg=0.8.0
  - urllib3=2.5.0
  - veracitools=0.1.3
  - wget=1.21.4
  - wheel=0.45.1
  - wrapt=1.17.3
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yte=1.8.1
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - anyio==4.11.0
      - astunparse==1.6.3
      - bio==1.8.1
      - biopython==1.86
      - biothings-client==0.4.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - edlib==1.3.9.post1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - gprofiler-official==1.0.0
      - grpcio==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - joblib==1.5.2
      - keras==3.12.0
      - kiwisolver==1.4.9
      - kmerhash==0.4.4
      - levenshtein==0.27.3
      - libclang==18.1.1
      - lmdb==1.7.5
      - markdown==3.10
      - matplotlib==3.10.7
      - ml-dtypes==0.5.3
      - msgpack==1.1.2
      - mygene==3.2.2
      - namex==0.1.0
      - natsort==8.4.0
      - ncls==0.0.70
      - networkx==3.5
      - opt-einsum==3.4.0
      - optree==0.17.0
      - pillow==12.0.0
      - pooch==1.8.2
      - protobuf==6.33.0
      - pybedtools==0.12.0
      - pyfaidx==0.9.0.3
      - pyranges==0.1.4
      - pysam==0.23.3
      - rapidfuzz==3.14.3
      - scikit-fuzzy==0.5.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sniffio==1.3.1
      - sorted-nearest==0.0.41
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - werkzeug==3.1.3
prefix: /home/jmhan/miniconda3/envs/com_decom
